// Lightweight i18n. t("key", {vars}) with {var} interpolation; falls back to
// English then the key itself. Language persists in localStorage.
export const LANGS = [
  { code: "nl", label: "Nederlands" },
  { code: "en", label: "English" },
  { code: "de", label: "Deutsch" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
  { code: "it", label: "Italiano" },
  { code: "pt", label: "Português" },
  { code: "pl", label: "Polski" },
  { code: "sv", label: "Svenska" },
  { code: "no", label: "Norsk" },
];

const STR = {
  // nav / chrome
  "nav.logbook": { nl: "Logboek", en: "Logbook", de: "Logbuch", fr: "Journal", es: "Cuaderno", it: "Registro", pt: "Registo", pl: "Dziennik", sv: "Loggbok", no: "Loggbok" },
  "nav.stats": { nl: "Statistieken", en: "Statistics", de: "Statistik", fr: "Statistiques", es: "Estadísticas", it: "Statistiche", pt: "Estatísticas", pl: "Statystyki", sv: "Statistik", no: "Statistikk" },
  "nav.upload": { nl: "Upload", en: "Upload", de: "Hochladen", fr: "Importer", es: "Subir", it: "Carica", pt: "Carregar", pl: "Prześlij", sv: "Ladda upp", no: "Last opp" },
  "live": { nl: "Live", en: "Live", de: "Live", fr: "Live", es: "En vivo", it: "Live", pt: "Ao vivo", pl: "Na żywo", sv: "Live", no: "Live" },
  "footer.tag": { nl: "Persoonlijke skydive-tracker · vrije-val-waarden zijn schattingen", en: "Personal skydive tracker · freefall values are estimates", de: "Persönlicher Fallschirm-Tracker · Freifall-Werte sind Schätzungen", fr: "Carnet de saut personnel · les valeurs en chute libre sont des estimations", es: "Registro personal de saltos · los valores en caída libre son estimaciones", it: "Tracker personale di paracadutismo · i valori in caduta libera sono stime", pt: "Registo pessoal de saltos · os valores em queda livre são estimativas", pl: "Osobisty dziennik skoków · wartości w swobodnym spadaniu są szacunkowe", sv: "Personlig hopplogg · värden i fritt fall är uppskattningar", no: "Personlig hopplogg · friflukt-verdier er anslag" },

  // common
  "btn.uploadFit": { nl: "Upload .FIT", en: "Upload .FIT", de: ".FIT hochladen", fr: "Importer .FIT", es: "Subir .FIT", it: "Carica .FIT", pt: "Carregar .FIT", pl: "Prześlij .FIT", sv: "Ladda upp .FIT", no: "Last opp .FIT" },
  "btn.save": { nl: "Opslaan", en: "Save", de: "Speichern", fr: "Enregistrer", es: "Guardar", it: "Salva", pt: "Guardar", pl: "Zapisz", sv: "Spara", no: "Lagre" },
  "btn.delete": { nl: "Verwijderen", en: "Delete", de: "Löschen", fr: "Supprimer", es: "Eliminar", it: "Elimina", pt: "Eliminar", pl: "Usuń", sv: "Radera", no: "Slett" },
  "btn.back": { nl: "Terug", en: "Back", de: "Zurück", fr: "Retour", es: "Atrás", it: "Indietro", pt: "Voltar", pl: "Wstecz", sv: "Tillbaka", no: "Tilbake" },
  "back.logbook": { nl: "Terug naar logboek", en: "Back to logbook", de: "Zurück zum Logbuch", fr: "Retour au journal", es: "Volver al cuaderno", it: "Torna al registro", pt: "Voltar ao registo", pl: "Powrót do dziennika", sv: "Tillbaka till loggboken", no: "Tilbake til loggboken" },
  "dz.unknown": { nl: "Onbekende dropzone", en: "Unknown dropzone", de: "Unbekannte Dropzone", fr: "Zone de saut inconnue", es: "Zona de salto desconocida", it: "Dropzone sconosciuta", pt: "Zona de salto desconhecida", pl: "Nieznana strefa zrzutu", sv: "Okänd hoppfält", no: "Ukjent hoppfelt" },
  "na": { nl: "Niet beschikbaar", en: "Not available", de: "Nicht verfügbar", fr: "Indisponible", es: "No disponible", it: "Non disponibile", pt: "Indisponível", pl: "Niedostępne", sv: "Ej tillgängligt", no: "Ikke tilgjengelig" },
  "noTarget": { nl: "Geen target", en: "No target", de: "Kein Ziel", fr: "Aucune cible", es: "Sin objetivo", it: "Nessun target", pt: "Sem alvo", pl: "Brak celu", sv: "Inget mål", no: "Inget mål" },
  "noGps": { nl: "Geen GPS", en: "No GPS", de: "Kein GPS", fr: "Pas de GPS", es: "Sin GPS", it: "Nessun GPS", pt: "Sem GPS", pl: "Brak GPS", sv: "Ingen GPS", no: "Ingen GPS" },
  "estimate": { nl: "schatting", en: "estimate", de: "Schätzung", fr: "estimation", es: "estimación", it: "stima", pt: "estimativa", pl: "szacunek", sv: "uppskattning", no: "anslag" },

  // phases
  "phase.climb": { nl: "Klim", en: "Climb", de: "Steigflug", fr: "Montée", es: "Ascenso", it: "Salita", pt: "Subida", pl: "Wznoszenie", sv: "Stigning", no: "Stigning" },
  "phase.exit": { nl: "Exit", en: "Exit", de: "Absprung", fr: "Sortie", es: "Salida", it: "Uscita", pt: "Saída", pl: "Wyskok", sv: "Uthopp", no: "Uthopp" },
  "phase.freefall": { nl: "Vrije val", en: "Freefall", de: "Freier Fall", fr: "Chute libre", es: "Caída libre", it: "Caduta libera", pt: "Queda livre", pl: "Swobodny spadek", sv: "Fritt fall", no: "Fritt fall" },
  "phase.canopy": { nl: "Canopy", en: "Canopy", de: "Schirm", fr: "Voile", es: "Vela", it: "Vela", pt: "Vela", pl: "Czasza", sv: "Skärm", no: "Skjerm" },
  "phase.landed": { nl: "Landing", en: "Landing", de: "Landung", fr: "Atterrissage", es: "Aterrizaje", it: "Atterraggio", pt: "Aterragem", pl: "Lądowanie", sv: "Landning", no: "Landing" },

  // logbook
  "logbook.title": { nl: "Logboek", en: "Logbook", de: "Logbuch", fr: "Journal de sauts", es: "Cuaderno de saltos", it: "Registro salti", pt: "Registo de saltos", pl: "Dziennik skoków", sv: "Hopplogg", no: "Hopplogg" },
  "logbook.subDefault": { nl: "Persoonlijk skydive-logboek", en: "Personal skydive logbook", de: "Persönliches Sprung-Logbuch", fr: "Carnet de saut personnel", es: "Cuaderno de saltos personal", it: "Registro salti personale", pt: "Registo de saltos pessoal", pl: "Osobisty dziennik skoków", sv: "Personlig hopplogg", no: "Personlig hopplogg" },
  "logbook.count": { nl: "{n} sprong{s} · synct automatisch", en: "{n} jump{s} · syncs automatically", de: "{n} Spr{s} · synchronisiert automatisch", fr: "{n} saut{s} · synchro automatique", es: "{n} salto{s} · se sincroniza solo", it: "{n} salto{s} · sincronizza da solo", pt: "{n} salto{s} · sincroniza sozinho", pl: "{n} skok{s} · synchronizuje się sam", sv: "{n} hopp · synkar automatiskt", no: "{n} hopp · synkroniserer selv" },
  "empty.noJumps.title": { nl: "Nog geen sprongen", en: "No jumps yet", de: "Noch keine Sprünge", fr: "Aucun saut pour l'instant", es: "Aún no hay saltos", it: "Ancora nessun salto", pt: "Ainda sem saltos", pl: "Brak skoków", sv: "Inga hopp ännu", no: "Ingen hopp ennå" },
  "empty.noJumps.text": { nl: "Upload een .FIT-bestand of maak je eerste opname met de Garmin-app. Nieuwe sprongen verschijnen hier automatisch.", en: "Upload a .FIT file or make your first recording with the Garmin app. New jumps appear here automatically.", de: "Lade eine .FIT-Datei hoch oder mache deine erste Aufzeichnung mit der Garmin-App. Neue Sprünge erscheinen hier automatisch.", fr: "Importez un fichier .FIT ou faites votre premier enregistrement avec l'app Garmin. Les nouveaux sauts apparaissent ici automatiquement.", es: "Sube un archivo .FIT o haz tu primera grabación con la app de Garmin. Los nuevos saltos aparecen aquí automáticamente.", it: "Carica un file .FIT o registra il primo salto con l'app Garmin. I nuovi salti appaiono qui automaticamente.", pt: "Carrega um ficheiro .FIT ou faz a tua primeira gravação na app Garmin. Os novos saltos aparecem aqui automaticamente.", pl: "Prześlij plik .FIT lub nagraj pierwszy skok aplikacją Garmin. Nowe skoki pojawią się tu automatycznie.", sv: "Ladda upp en .FIT-fil eller gör din första inspelning med Garmin-appen. Nya hopp dyker upp här automatiskt.", no: "Last opp en .FIT-fil eller gjør ditt første opptak med Garmin-appen. Nye hopp vises her automatisk." },
  "toast.newJump": { nl: "Nieuwe sprong binnengekomen", en: "New jump received", de: "Neuer Sprung empfangen", fr: "Nouveau saut reçu", es: "Nuevo salto recibido", it: "Nuovo salto ricevuto", pt: "Novo salto recebido", pl: "Otrzymano nowy skok", sv: "Nytt hopp mottaget", no: "Nytt hopp mottatt" },
  "jump.delete": { nl: "Verwijder sprong", en: "Delete jump", de: "Sprung löschen", fr: "Supprimer le saut", es: "Eliminar salto", it: "Elimina salto", pt: "Eliminar salto", pl: "Usuń skok", sv: "Radera hopp", no: "Slett hopp" },
  "jump.deleteConfirm": { nl: "Sprong #{n} verwijderen?", en: "Delete jump #{n}?", de: "Sprung #{n} löschen?", fr: "Supprimer le saut #{n} ?", es: "¿Eliminar el salto #{n}?", it: "Eliminare il salto #{n}?", pt: "Eliminar o salto #{n}?", pl: "Usunąć skok #{n}?", sv: "Radera hopp #{n}?", no: "Slette hopp #{n}?" },
  "toast.deleted": { nl: "Sprong verwijderd", en: "Jump deleted", de: "Sprung gelöscht", fr: "Saut supprimé", es: "Salto eliminado", it: "Salto eliminato", pt: "Salto eliminado", pl: "Skok usunięty", sv: "Hopp raderat", no: "Hopp slettet" },
  "toast.deleteFail": { nl: "Verwijderen mislukt: {e}", en: "Delete failed: {e}", de: "Löschen fehlgeschlagen: {e}", fr: "Échec de la suppression : {e}", es: "Error al eliminar: {e}", it: "Eliminazione non riuscita: {e}", pt: "Falha ao eliminar: {e}", pl: "Usuwanie nie powiodło się: {e}", sv: "Radering misslyckades: {e}", no: "Sletting mislyktes: {e}" },

  // detail
  "detail.eyebrow": { nl: "Sprongdetail", en: "Jump detail", de: "Sprungdetails", fr: "Détail du saut", es: "Detalle del salto", it: "Dettaglio salto", pt: "Detalhe do salto", pl: "Szczegóły skoku", sv: "Hoppdetaljer", no: "Hoppdetaljer" },
  "jump.n": { nl: "Sprong #{n}", en: "Jump #{n}", de: "Sprung #{n}", fr: "Saut #{n}", es: "Salto #{n}", it: "Salto #{n}", pt: "Salto #{n}", pl: "Skok #{n}", sv: "Hopp #{n}", no: "Hopp #{n}" },
  "panel.timeline": { nl: "Sprongverloop", en: "Jump timeline", de: "Sprungverlauf", fr: "Déroulé du saut", es: "Cronología del salto", it: "Andamento del salto", pt: "Cronologia do salto", pl: "Przebieg skoku", sv: "Hoppförlopp", no: "Hoppforløp" },
  "m.exitAlt": { nl: "Exit-hoogte", en: "Exit altitude", de: "Absprunghöhe", fr: "Altitude de sortie", es: "Altitud de salida", it: "Quota di uscita", pt: "Altitude de saída", pl: "Wysokość wyskoku", sv: "Uthoppshöjd", no: "Uthoppshøyde" },
  "m.peakVs": { nl: "Piek daalsnelheid", en: "Peak descent rate", de: "Max. Sinkrate", fr: "Vitesse de chute max", es: "Velocidad de caída máx", it: "Velocità di caduta max", pt: "Velocidade de queda máx", pl: "Maks. prędkość opadania", sv: "Max fallhastighet", no: "Maks fallhastighet" },
  "m.avgVs": { nl: "Gem. daalsnelheid", en: "Avg descent rate", de: "Ø Sinkrate", fr: "Vitesse de chute moy", es: "Velocidad de caída med", it: "Velocità di caduta media", pt: "Velocidade de queda média", pl: "Śr. prędkość opadania", sv: "Snitt fallhastighet", no: "Snitt fallhastighet" },
  "m.peakHr": { nl: "Piek hartslag", en: "Peak heart rate", de: "Max. Herzfrequenz", fr: "Fréq. cardiaque max", es: "Frec. cardíaca máx", it: "Freq. cardiaca max", pt: "Freq. cardíaca máx", pl: "Maks. tętno", sv: "Max puls", no: "Maks puls" },
  "m.avgHr": { nl: "Gem. hartslag", en: "Avg heart rate", de: "Ø Herzfrequenz", fr: "Fréq. cardiaque moy", es: "Frec. cardíaca med", it: "Freq. cardiaca media", pt: "Freq. cardíaca média", pl: "Śr. tętno", sv: "Snittpuls", no: "Snittpuls" },
  "m.maxGround": { nl: "Max grondsnelheid", en: "Max ground speed", de: "Max. Bodengeschw.", fr: "Vitesse sol max", es: "Velocidad en tierra máx", it: "Velocità al suolo max", pt: "Velocidade no solo máx", pl: "Maks. prędkość nad ziemią", sv: "Max markfart", no: "Maks bakkefart" },
  "m.drift": { nl: "Horizontale drift", en: "Horizontal drift", de: "Horizontale Drift", fr: "Dérive horizontale", es: "Deriva horizontal", it: "Deriva orizzontale", pt: "Deriva horizontal", pl: "Dryf poziomy", sv: "Horisontell drift", no: "Horisontal drift" },
  "m.distTarget": { nl: "Afstand tot target", en: "Distance to target", de: "Distanz zum Ziel", fr: "Distance à la cible", es: "Distancia al objetivo", it: "Distanza dal target", pt: "Distância ao alvo", pl: "Odległość do celu", sv: "Avstånd till mål", no: "Avstand til mål" },

  // status badges
  "badge.fit": { nl: ".FIT-import", en: ".FIT import", de: ".FIT-Import", fr: "Import .FIT", es: "Importación .FIT", it: "Import .FIT", pt: "Importação .FIT", pl: "Import .FIT", sv: ".FIT-import", no: ".FIT-import" },
  "badge.watch": { nl: "Watch-sync", en: "Watch sync", de: "Uhren-Sync", fr: "Sync montre", es: "Sinc. reloj", it: "Sync orologio", pt: "Sync relógio", pl: "Synch. zegarka", sv: "Klock-synk", no: "Klokke-synk" },
  "badge.noFreefall": { nl: "Geen vrije val gedetecteerd", en: "No freefall detected", de: "Kein freier Fall erkannt", fr: "Aucune chute libre détectée", es: "No se detectó caída libre", it: "Nessuna caduta libera rilevata", pt: "Nenhuma queda livre detetada", pl: "Nie wykryto swobodnego spadania", sv: "Inget fritt fall hittat", no: "Ingen fritt fall oppdaget" },
  "badge.noGps": { nl: "GPS ontbreekt", en: "GPS missing", de: "GPS fehlt", fr: "GPS manquant", es: "Falta GPS", it: "GPS assente", pt: "GPS em falta", pl: "Brak GPS", sv: "GPS saknas", no: "GPS mangler" },
  "badge.estimates": { nl: "Bevat schattingen", en: "Contains estimates", de: "Enthält Schätzungen", fr: "Contient des estimations", es: "Contiene estimaciones", it: "Contiene stime", pt: "Contém estimativas", pl: "Zawiera szacunki", sv: "Innehåller uppskattningar", no: "Inneholder anslag" },
  "note.noFreefall": { nl: "Geen vrije val gedetecteerd (bv. een grondtest of trage daling). Fases en samenvatting zijn een beste schatting.", en: "No freefall detected (e.g. a ground test or slow descent). Phases and summary are a best estimate.", de: "Kein freier Fall erkannt (z. B. ein Bodentest oder langsamer Sinkflug). Phasen und Zusammenfassung sind eine Schätzung.", fr: "Aucune chute libre détectée (ex. test au sol ou descente lente). Les phases et le résumé sont une estimation.", es: "No se detectó caída libre (p. ej. prueba en tierra o descenso lento). Las fases y el resumen son una estimación.", it: "Nessuna caduta libera rilevata (es. test a terra o discesa lenta). Fasi e riepilogo sono una stima.", pt: "Nenhuma queda livre detetada (ex. teste no solo ou descida lenta). As fases e o resumo são uma estimativa.", pl: "Nie wykryto swobodnego spadania (np. test naziemny lub wolne opadanie). Fazy i podsumowanie to przybliżenie.", sv: "Inget fritt fall hittat (t.ex. marktest eller långsam nedstigning). Faser och sammanfattning är en uppskattning.", no: "Ingen fritt fall oppdaget (f.eks. en bakketest eller langsom nedstigning). Faser og sammendrag er et anslag." },

  // tracking
  "panel.tracking": { nl: "Tracking & wingsuit", en: "Tracking & wingsuit", de: "Tracking & Wingsuit", fr: "Tracking & wingsuit", es: "Tracking y wingsuit", it: "Tracking e wingsuit", pt: "Tracking e wingsuit", pl: "Tracking i wingsuit", sv: "Tracking & wingsuit", no: "Tracking & wingsuit" },
  "m.glide": { nl: "Glijgetal", en: "Glide ratio", de: "Gleitzahl", fr: "Finesse", es: "Planeo", it: "Efficienza", pt: "Planeio", pl: "Doskonałość", sv: "Glidtal", no: "Glidetall" },
  "m.avgHoriz": { nl: "Gem. horiz. snelheid", en: "Avg horizontal speed", de: "Ø Horizontalgeschw.", fr: "Vitesse horiz. moy", es: "Velocidad horiz. med", it: "Velocità orizz. media", pt: "Velocidade horiz. média", pl: "Śr. prędkość pozioma", sv: "Snitt horisontalfart", no: "Snitt horisontalfart" },
  "m.peakHoriz": { nl: "Piek horiz. snelheid", en: "Peak horizontal speed", de: "Max. Horizontalgeschw.", fr: "Vitesse horiz. max", es: "Velocidad horiz. máx", it: "Velocità orizz. max", pt: "Velocidade horiz. máx", pl: "Maks. prędkość pozioma", sv: "Max horisontalfart", no: "Maks horisontalfart" },
  "m.horizDist": { nl: "Horizontale afstand", en: "Horizontal distance", de: "Horizontale Distanz", fr: "Distance horizontale", es: "Distancia horizontal", it: "Distanza orizzontale", pt: "Distância horizontal", pl: "Odległość pozioma", sv: "Horisontellt avstånd", no: "Horisontal avstand" },

  // edit
  "edit.title": { nl: "Bewerk sprong", en: "Edit jump", de: "Sprung bearbeiten", fr: "Modifier le saut", es: "Editar salto", it: "Modifica salto", pt: "Editar salto", pl: "Edytuj skok", sv: "Redigera hopp", no: "Rediger hopp" },
  "edit.info": { nl: "Sprong-info", en: "Jump info", de: "Sprung-Info", fr: "Infos du saut", es: "Datos del salto", it: "Info salto", pt: "Info do salto", pl: "Informacje o skoku", sv: "Hoppinfo", no: "Hoppinfo" },
  "field.type": { nl: "Type", en: "Type", de: "Typ", fr: "Type", es: "Tipo", it: "Tipo", pt: "Tipo", pl: "Typ", sv: "Typ", no: "Type" },
  "field.aircraft": { nl: "Vliegtuig", en: "Aircraft", de: "Flugzeug", fr: "Avion", es: "Avión", it: "Aereo", pt: "Avião", pl: "Samolot", sv: "Flygplan", no: "Fly" },
  "field.jumpNumber": { nl: "Sprongnummer", en: "Jump number", de: "Sprungnummer", fr: "Numéro de saut", es: "Número de salto", it: "Numero salto", pt: "Número do salto", pl: "Numer skoku", sv: "Hoppnummer", no: "Hoppnummer" },
  "edit.target": { nl: "Target-locatie", en: "Target location", de: "Zielposition", fr: "Position cible", es: "Ubicación objetivo", it: "Posizione target", pt: "Localização do alvo", pl: "Lokalizacja celu", sv: "Målposition", no: "Målposisjon" },
  "field.lat": { nl: "Latitude", en: "Latitude", de: "Breitengrad", fr: "Latitude", es: "Latitud", it: "Latitudine", pt: "Latitude", pl: "Szerokość", sv: "Latitud", no: "Breddegrad" },
  "field.lng": { nl: "Longitude", en: "Longitude", de: "Längengrad", fr: "Longitude", es: "Longitud", it: "Longitudine", pt: "Longitude", pl: "Długość", sv: "Longitud", no: "Lengdegrad" },
  "field.targetHint": { nl: "Zet je beoogde landingspunt om de afstand tot target te berekenen.", en: "Set your intended landing point to compute the distance to target.", de: "Lege deinen geplanten Landepunkt fest, um die Distanz zum Ziel zu berechnen.", fr: "Définissez votre point d'atterrissage visé pour calculer la distance à la cible.", es: "Define tu punto de aterrizaje previsto para calcular la distancia al objetivo.", it: "Imposta il punto di atterraggio previsto per calcolare la distanza dal target.", pt: "Define o teu ponto de aterragem pretendido para calcular a distância ao alvo.", pl: "Ustaw planowane miejsce lądowania, aby obliczyć odległość do celu.", sv: "Ange din tänkta landningspunkt för att räkna ut avståndet till målet.", no: "Angi ønsket landingspunkt for å beregne avstanden til målet." },
  "edit.notes": { nl: "Notities", en: "Notes", de: "Notizen", fr: "Notes", es: "Notas", it: "Note", pt: "Notas", pl: "Notatki", sv: "Anteckningar", no: "Notater" },
  "notes.placeholder": { nl: "Vrije notities over deze sprong…", en: "Free notes about this jump…", de: "Freie Notizen zu diesem Sprung…", fr: "Notes libres sur ce saut…", es: "Notas libres sobre este salto…", it: "Note libere su questo salto…", pt: "Notas livres sobre este salto…", pl: "Dowolne notatki o tym skoku…", sv: "Fria anteckningar om hoppet…", no: "Frie notater om dette hoppet…" },
  "type.placeholder": { nl: "— kies type —", en: "— choose type —", de: "— Typ wählen —", fr: "— choisir le type —", es: "— elige tipo —", it: "— scegli tipo —", pt: "— escolhe o tipo —", pl: "— wybierz typ —", sv: "— välj typ —", no: "— velg type —" },
  "del.confirmShort": { nl: "Zeker weten?", en: "Are you sure?", de: "Sicher?", fr: "Confirmer ?", es: "¿Seguro?", it: "Sei sicuro?", pt: "Tens a certeza?", pl: "Na pewno?", sv: "Säker?", no: "Sikker?" },
  "del.yes": { nl: "Ja, verwijder", en: "Yes, delete", de: "Ja, löschen", fr: "Oui, supprimer", es: "Sí, eliminar", it: "Sì, elimina", pt: "Sim, eliminar", pl: "Tak, usuń", sv: "Ja, radera", no: "Ja, slett" },
  "del.cancel": { nl: "Annuleer", en: "Cancel", de: "Abbrechen", fr: "Annuler", es: "Cancelar", it: "Annulla", pt: "Cancelar", pl: "Anuluj", sv: "Avbryt", no: "Avbryt" },
  "toast.saved": { nl: "Opgeslagen", en: "Saved", de: "Gespeichert", fr: "Enregistré", es: "Guardado", it: "Salvato", pt: "Guardado", pl: "Zapisano", sv: "Sparat", no: "Lagret" },
  "toast.saveFail": { nl: "Opslaan mislukt: {e}", en: "Save failed: {e}", de: "Speichern fehlgeschlagen: {e}", fr: "Échec de l'enregistrement : {e}", es: "Error al guardar: {e}", it: "Salvataggio non riuscito: {e}", pt: "Falha ao guardar: {e}", pl: "Zapis nie powiódł się: {e}", sv: "Sparandet misslyckades: {e}", no: "Lagring mislyktes: {e}" },

  // map / 3d / charts
  "panel.map": { nl: "Kaart — grondtrack", en: "Map — ground track", de: "Karte — Bodenspur", fr: "Carte — trace au sol", es: "Mapa — trayectoria en tierra", it: "Mappa — traccia al suolo", pt: "Mapa — trajeto no solo", pl: "Mapa — ślad naziemny", sv: "Karta — markspår", no: "Kart — bakkespor" },
  "panel.3d": { nl: "3D-sprongtrack", en: "3D jump track", de: "3D-Sprungspur", fr: "Trace 3D du saut", es: "Trayectoria 3D del salto", it: "Traccia 3D del salto", pt: "Trajeto 3D do salto", pl: "Ślad skoku 3D", sv: "3D-hoppspår", no: "3D-hoppspor" },
  "map.noGps": { nl: "Deze opname bevat geen GPS-posities, dus er is geen kaart te tonen.", en: "This recording has no GPS positions, so there's no map to show.", de: "Diese Aufzeichnung enthält keine GPS-Positionen, daher gibt es keine Karte.", fr: "Cet enregistrement n'a pas de positions GPS, aucune carte à afficher.", es: "Esta grabación no tiene posiciones GPS, no hay mapa que mostrar.", it: "Questa registrazione non ha posizioni GPS, nessuna mappa da mostrare.", pt: "Esta gravação não tem posições GPS, não há mapa para mostrar.", pl: "To nagranie nie ma pozycji GPS, brak mapy do pokazania.", sv: "Inspelningen saknar GPS-positioner, ingen karta att visa.", no: "Dette opptaket har ingen GPS-posisjoner, ingen kart å vise." },
  "threeD.noGps": { nl: "Geen GPS-track beschikbaar voor 3D-weergave.", en: "No GPS track available for 3D view.", de: "Keine GPS-Spur für die 3D-Ansicht verfügbar.", fr: "Aucune trace GPS pour la vue 3D.", es: "No hay traza GPS para la vista 3D.", it: "Nessuna traccia GPS per la vista 3D.", pt: "Sem traço GPS para a vista 3D.", pl: "Brak śladu GPS do widoku 3D.", sv: "Ingen GPS-spår för 3D-vyn.", no: "Ingen GPS-spor for 3D-visning." },
  "chart.altTime": { nl: "Hoogte vs tijd", en: "Altitude vs time", de: "Höhe vs Zeit", fr: "Altitude / temps", es: "Altitud vs tiempo", it: "Quota vs tempo", pt: "Altitude vs tempo", pl: "Wysokość vs czas", sv: "Höjd mot tid", no: "Høyde mot tid" },
  "chart.vsTime": { nl: "Daalsnelheid vs tijd", en: "Descent rate vs time", de: "Sinkrate vs Zeit", fr: "Vitesse de chute / temps", es: "Velocidad de caída vs tiempo", it: "Velocità di caduta vs tempo", pt: "Velocidade de queda vs tempo", pl: "Prędkość opadania vs czas", sv: "Fallhastighet mot tid", no: "Fallhastighet mot tid" },
  "chart.hrTime": { nl: "Hartslag vs tijd", en: "Heart rate vs time", de: "Herzfrequenz vs Zeit", fr: "Fréq. cardiaque / temps", es: "Frec. cardíaca vs tiempo", it: "Freq. cardiaca vs tempo", pt: "Freq. cardíaca vs tempo", pl: "Tętno vs czas", sv: "Puls mot tid", no: "Puls mot tid" },
  "chart.groundCanopy": { nl: "Grondsnelheid — canopy", en: "Ground speed — canopy", de: "Bodengeschw. — Schirm", fr: "Vitesse sol — voile", es: "Velocidad en tierra — vela", it: "Velocità al suolo — vela", pt: "Velocidade no solo — vela", pl: "Prędkość nad ziemią — czasza", sv: "Markfart — skärm", no: "Bakkefart — skjerm" },
  "chart.combined": { nl: "Hoogte + daalsnelheid", en: "Altitude + descent rate", de: "Höhe + Sinkrate", fr: "Altitude + vitesse de chute", es: "Altitud + velocidad de caída", it: "Quota + velocità di caduta", pt: "Altitude + velocidade de queda", pl: "Wysokość + prędkość opadania", sv: "Höjd + fallhastighet", no: "Høyde + fallhastighet" },
  "chart.noData": { nl: "Geen data", en: "No data", de: "Keine Daten", fr: "Aucune donnée", es: "Sin datos", it: "Nessun dato", pt: "Sem dados", pl: "Brak danych", sv: "Inga data", no: "Ingen data" },
  "chart.noDataText": { nl: "Voor deze grafiek is geen data beschikbaar in deze sprong.", en: "No data available for this chart in this jump.", de: "Für dieses Diagramm sind in diesem Sprung keine Daten verfügbar.", fr: "Aucune donnée pour ce graphique dans ce saut.", es: "No hay datos para este gráfico en este salto.", it: "Nessun dato per questo grafico in questo salto.", pt: "Sem dados para este gráfico neste salto.", pl: "Brak danych do tego wykresu w tym skoku.", sv: "Inga data för detta diagram i hoppet.", no: "Ingen data for dette diagrammet i dette hoppet." },

  // stats
  "stats.title": { nl: "Statistieken", en: "Statistics", de: "Statistik", fr: "Statistiques", es: "Estadísticas", it: "Statistiche", pt: "Estatísticas", pl: "Statystyki", sv: "Statistik", no: "Statistikk" },
  "stats.subAuto": { nl: "Cumulatieve cijfers en trends · vernieuwt automatisch", en: "Cumulative figures and trends · refreshes automatically", de: "Kumulative Zahlen und Trends · aktualisiert automatisch", fr: "Chiffres cumulés et tendances · rafraîchi automatiquement", es: "Cifras acumuladas y tendencias · se actualiza solo", it: "Dati cumulativi e tendenze · si aggiorna da solo", pt: "Números acumulados e tendências · atualiza sozinho", pl: "Dane skumulowane i trendy · odświeża się sam", sv: "Kumulativa siffror och trender · uppdateras automatiskt", no: "Kumulative tall og trender · oppdateres automatisk" },
  "stats.subDefault": { nl: "Cumulatieve cijfers en trends over al je sprongen", en: "Cumulative figures and trends across all your jumps", de: "Kumulative Zahlen und Trends über alle Sprünge", fr: "Chiffres cumulés et tendances sur tous vos sauts", es: "Cifras acumuladas y tendencias de todos tus saltos", it: "Dati cumulativi e tendenze su tutti i salti", pt: "Números acumulados e tendências de todos os saltos", pl: "Dane skumulowane i trendy ze wszystkich skoków", sv: "Kumulativa siffror och trender över alla hopp", no: "Kumulative tall og trender over alle hopp" },
  "stats.emptyTitle": { nl: "Nog geen statistieken", en: "No statistics yet", de: "Noch keine Statistik", fr: "Pas encore de statistiques", es: "Aún no hay estadísticas", it: "Ancora nessuna statistica", pt: "Ainda sem estatísticas", pl: "Brak statystyk", sv: "Ingen statistik ännu", no: "Ingen statistikk ennå" },
  "stats.emptyText": { nl: "Zodra je eerste sprong binnen is, verschijnen hier je totalen en trends.", en: "Once your first jump arrives, your totals and trends appear here.", de: "Sobald dein erster Sprung da ist, erscheinen hier Summen und Trends.", fr: "Dès votre premier saut, vos totaux et tendances apparaîtront ici.", es: "En cuanto llegue tu primer salto, aquí verás tus totales y tendencias.", it: "Appena arriva il primo salto, qui appariranno totali e tendenze.", pt: "Assim que chegar o teu primeiro salto, aparecem aqui os totais e tendências.", pl: "Gdy pojawi się pierwszy skok, zobaczysz tu sumy i trendy.", sv: "Så snart ditt första hopp kommit in visas summor och trender här.", no: "Når ditt første hopp er inne, vises totaler og trender her." },
  "records.title": { nl: "Persoonlijke records", en: "Personal records", de: "Persönliche Rekorde", fr: "Records personnels", es: "Récords personales", it: "Record personali", pt: "Recordes pessoais", pl: "Rekordy osobiste", sv: "Personliga rekord", no: "Personlige rekorder" },
  "rec.exit": { nl: "Hoogste exit", en: "Highest exit", de: "Höchster Absprung", fr: "Sortie la plus haute", es: "Salida más alta", it: "Uscita più alta", pt: "Saída mais alta", pl: "Najwyższy wyskok", sv: "Högsta uthopp", no: "Høyeste uthopp" },
  "rec.freefall": { nl: "Langste vrije val", en: "Longest freefall", de: "Längster freier Fall", fr: "Plus longue chute libre", es: "Caída libre más larga", it: "Caduta libera più lunga", pt: "Queda livre mais longa", pl: "Najdłuższy swobodny spadek", sv: "Längsta fritt fall", no: "Lengste fritt fall" },
  "rec.hr": { nl: "Hoogste hartslag", en: "Highest heart rate", de: "Höchste Herzfrequenz", fr: "Fréq. cardiaque max", es: "Frec. cardíaca más alta", it: "Freq. cardiaca più alta", pt: "Freq. cardíaca mais alta", pl: "Najwyższe tętno", sv: "Högsta puls", no: "Høyeste puls" },
  "rec.ground": { nl: "Hoogste grondsnelheid", en: "Highest ground speed", de: "Höchste Bodengeschw.", fr: "Vitesse sol max", es: "Velocidad en tierra máx", it: "Velocità al suolo max", pt: "Velocidade no solo máx", pl: "Najwyższa prędkość nad ziemią", sv: "Högsta markfart", no: "Høyeste bakkefart" },
  "rec.glide": { nl: "Beste glijgetal", en: "Best glide ratio", de: "Beste Gleitzahl", fr: "Meilleure finesse", es: "Mejor planeo", it: "Migliore efficienza", pt: "Melhor planeio", pl: "Najlepsza doskonałość", sv: "Bästa glidtal", no: "Beste glidetall" },
  "rec.jumpN": { nl: "Sprong #{n}", en: "Jump #{n}", de: "Sprung #{n}", fr: "Saut #{n}", es: "Salto #{n}", it: "Salto #{n}", pt: "Salto #{n}", pl: "Skok #{n}", sv: "Hopp #{n}", no: "Hopp #{n}" },
  "cur.last30": { nl: "Laatste 30 dagen", en: "Last 30 days", de: "Letzte 30 Tage", fr: "30 derniers jours", es: "Últimos 30 días", it: "Ultimi 30 giorni", pt: "Últimos 30 dias", pl: "Ostatnie 30 dni", sv: "Senaste 30 dagar", no: "Siste 30 dager" },
  "cur.last90": { nl: "Laatste 90 dagen", en: "Last 90 days", de: "Letzte 90 Tage", fr: "90 derniers jours", es: "Últimos 90 días", it: "Ultimi 90 giorni", pt: "Últimos 90 dias", pl: "Ostatnie 90 dni", sv: "Senaste 90 dagar", no: "Siste 90 dager" },
  "cur.avgMonth": { nl: "Gem. per maand", en: "Avg per month", de: "Ø pro Monat", fr: "Moy. par mois", es: "Med. por mes", it: "Media al mese", pt: "Média por mês", pl: "Śr. na miesiąc", sv: "Snitt per månad", no: "Snitt per måned" },
  "cur.gap": { nl: "Langste pauze", en: "Longest gap", de: "Längste Pause", fr: "Plus longue pause", es: "Pausa más larga", it: "Pausa più lunga", pt: "Maior intervalo", pl: "Najdłuższa przerwa", sv: "Längsta uppehåll", no: "Lengste opphold" },
  "cur.jumpsN": { nl: "{n} sprong{s}", en: "{n} jump{s}", de: "{n} Spr{s}", fr: "{n} saut{s}", es: "{n} salto{s}", it: "{n} salto{s}", pt: "{n} salto{s}", pl: "{n} skok{s}", sv: "{n} hopp", no: "{n} hopp" },
  "sec.trends": { nl: "Trends over tijd", en: "Trends over time", de: "Trends über die Zeit", fr: "Tendances dans le temps", es: "Tendencias en el tiempo", it: "Tendenze nel tempo", pt: "Tendências ao longo do tempo", pl: "Trendy w czasie", sv: "Trender över tid", no: "Trender over tid" },
  "sec.distributions": { nl: "Verdelingen", en: "Distributions", de: "Verteilungen", fr: "Répartitions", es: "Distribuciones", it: "Distribuzioni", pt: "Distribuições", pl: "Rozkłady", sv: "Fördelningar", no: "Fordelinger" },
  "chart.hrPerJump": { nl: "Hartslag per sprong", en: "Heart rate per jump", de: "Herzfrequenz pro Sprung", fr: "Fréq. cardiaque par saut", es: "Frec. cardíaca por salto", it: "Freq. cardiaca per salto", pt: "Freq. cardíaca por salto", pl: "Tętno na skok", sv: "Puls per hopp", no: "Puls per hopp" },
  "chart.hrZones": { nl: "Hartslag-zones (totaal)", en: "Heart-rate zones (total)", de: "Herzfrequenz-Zonen (gesamt)", fr: "Zones cardiaques (total)", es: "Zonas de frec. cardíaca (total)", it: "Zone cardiache (totale)", pt: "Zonas de freq. cardíaca (total)", pl: "Strefy tętna (łącznie)", sv: "Pulszoner (totalt)", no: "Pulssoner (totalt)" },
  "chart.exitFf": { nl: "Exit-hoogte & vrije val", en: "Exit altitude & freefall", de: "Absprunghöhe & freier Fall", fr: "Altitude de sortie & chute libre", es: "Altitud de salida y caída libre", it: "Quota di uscita e caduta libera", pt: "Altitude de saída e queda livre", pl: "Wysokość wyskoku i swobodny spadek", sv: "Uthoppshöjd & fritt fall", no: "Uthoppshøyde & fritt fall" },
  "chart.glideTrend": { nl: "Glijgetal-trend (tracking/wingsuit)", en: "Glide ratio trend (tracking/wingsuit)", de: "Gleitzahl-Trend (Tracking/Wingsuit)", fr: "Tendance de finesse (tracking/wingsuit)", es: "Tendencia de planeo (tracking/wingsuit)", it: "Tendenza efficienza (tracking/wingsuit)", pt: "Tendência de planeio (tracking/wingsuit)", pl: "Trend doskonałości (tracking/wingsuit)", sv: "Glidtal-trend (tracking/wingsuit)", no: "Glidetall-trend (tracking/wingsuit)" },
  "chart.perMonth": { nl: "Sprongen per maand", en: "Jumps per month", de: "Sprünge pro Monat", fr: "Sauts par mois", es: "Saltos por mes", it: "Salti al mese", pt: "Saltos por mês", pl: "Skoki na miesiąc", sv: "Hopp per månad", no: "Hopp per måned" },
  "chart.perType": { nl: "Sprongen per type", en: "Jumps per type", de: "Sprünge pro Typ", fr: "Sauts par type", es: "Saltos por tipo", it: "Salti per tipo", pt: "Saltos por tipo", pl: "Skoki wg typu", sv: "Hopp per typ", no: "Hopp per type" },
  "chart.perDz": { nl: "Sprongen per dropzone", en: "Jumps per dropzone", de: "Sprünge pro Dropzone", fr: "Sauts par zone de saut", es: "Saltos por zona", it: "Salti per dropzone", pt: "Saltos por zona", pl: "Skoki wg strefy", sv: "Hopp per hoppfält", no: "Hopp per hoppfelt" },
  "chart.exitDist": { nl: "Verdeling exit-hoogtes", en: "Exit altitude distribution", de: "Verteilung Absprunghöhen", fr: "Répartition des altitudes de sortie", es: "Distribución de altitudes de salida", it: "Distribuzione quote di uscita", pt: "Distribuição de altitudes de saída", pl: "Rozkład wysokości wyskoku", sv: "Fördelning av uthoppshöjder", no: "Fordeling av uthoppshøyder" },
  "chart.cumFf": { nl: "Cumulatieve vrije-val-tijd", en: "Cumulative freefall time", de: "Kumulative Freifallzeit", fr: "Temps de chute libre cumulé", es: "Tiempo de caída libre acumulado", it: "Tempo di caduta libera cumulativo", pt: "Tempo de queda livre acumulado", pl: "Skumulowany czas swobodnego spadania", sv: "Kumulativ friflukttid", no: "Kumulativ fritt fall-tid" },
  "ov.total": { nl: "Totaal sprongen", en: "Total jumps", de: "Sprünge gesamt", fr: "Sauts au total", es: "Saltos totales", it: "Salti totali", pt: "Saltos no total", pl: "Łącznie skoków", sv: "Totalt antal hopp", no: "Totalt antall hopp" },
  "ov.lastJump": { nl: "Laatste sprong", en: "Last jump", de: "Letzter Sprung", fr: "Dernier saut", es: "Último salto", it: "Ultimo salto", pt: "Último salto", pl: "Ostatni skok", sv: "Senaste hopp", no: "Siste hopp" },
  "ov.totalFf": { nl: "Totale vrije val", en: "Total freefall", de: "Freier Fall gesamt", fr: "Chute libre totale", es: "Caída libre total", it: "Caduta libera totale", pt: "Queda livre total", pl: "Łączny swobodny spadek", sv: "Totalt fritt fall", no: "Totalt fritt fall" },
  "ov.avgFf": { nl: "Gem. vrije val", en: "Avg freefall", de: "Ø freier Fall", fr: "Chute libre moy", es: "Caída libre med", it: "Caduta libera media", pt: "Queda livre média", pl: "Śr. swobodny spadek", sv: "Snitt fritt fall", no: "Snitt fritt fall" },
  "ov.highestExit": { nl: "Hoogste exit", en: "Highest exit", de: "Höchster Absprung", fr: "Sortie la plus haute", es: "Salida más alta", it: "Uscita più alta", pt: "Saída mais alta", pl: "Najwyższy wyskok", sv: "Högsta uthopp", no: "Høyeste uthopp" },
  "ov.avgExit": { nl: "Gem. exit-hoogte", en: "Avg exit altitude", de: "Ø Absprunghöhe", fr: "Altitude de sortie moy", es: "Altitud de salida med", it: "Quota di uscita media", pt: "Altitude de saída média", pl: "Śr. wysokość wyskoku", sv: "Snitt uthoppshöjd", no: "Snitt uthoppshøyde" },
  "today": { nl: "Vandaag", en: "Today", de: "Heute", fr: "Aujourd'hui", es: "Hoy", it: "Oggi", pt: "Hoje", pl: "Dziś", sv: "Idag", no: "I dag" },
  "daysAgo": { nl: "dagen geleden", en: "days ago", de: "Tage her", fr: "jours", es: "días atrás", it: "giorni fa", pt: "dias atrás", pl: "dni temu", sv: "dagar sedan", no: "dager siden" },
  "dayAgo": { nl: "dag geleden", en: "day ago", de: "Tag her", fr: "jour", es: "día atrás", it: "giorno fa", pt: "dia atrás", pl: "dzień temu", sv: "dag sedan", no: "dag siden" },
  "unit.days": { nl: "dgn", en: "days", de: "Tage", fr: "j", es: "días", it: "gg", pt: "dias", pl: "dni", sv: "dgr", no: "dgr" },

  // upload
  "upload.title": { nl: "Upload .FIT-bestand", en: "Upload .FIT file", de: ".FIT-Datei hochladen", fr: "Importer un fichier .FIT", es: "Subir archivo .FIT", it: "Carica file .FIT", pt: "Carregar ficheiro .FIT", pl: "Prześlij plik .FIT", sv: "Ladda upp .FIT-fil", no: "Last opp .FIT-fil" },
  "upload.sub": { nl: "Exporteer een activiteit van je Garmin als .FIT en sleep hem hierheen. Wordt server-side geparsed in hetzelfde datamodel als een live opname.", en: "Export an activity from your Garmin as .FIT and drop it here. It's parsed server-side into the same data model as a live recording.", de: "Exportiere eine Aktivität deiner Garmin als .FIT und zieh sie hierher. Sie wird serverseitig in dasselbe Datenmodell wie eine Live-Aufzeichnung umgewandelt.", fr: "Exportez une activité de votre Garmin en .FIT et déposez-la ici. Elle est analysée côté serveur dans le même modèle de données qu'un enregistrement live.", es: "Exporta una actividad de tu Garmin como .FIT y suéltala aquí. Se procesa en el servidor con el mismo modelo de datos que una grabación en vivo.", it: "Esporta un'attività dal tuo Garmin come .FIT e trascinala qui. Viene elaborata lato server nello stesso modello dati di una registrazione live.", pt: "Exporta uma atividade do teu Garmin como .FIT e arrasta-a para aqui. É processada no servidor no mesmo modelo de dados de uma gravação ao vivo.", pl: "Wyeksportuj aktywność z Garmina jako .FIT i upuść tutaj. Jest przetwarzana po stronie serwera w tym samym modelu danych co nagranie na żywo.", sv: "Exportera en aktivitet från din Garmin som .FIT och släpp den här. Den tolkas på servern till samma datamodell som en liveinspelning.", no: "Eksporter en aktivitet fra Garmin som .FIT og slipp den her. Den tolkes på serveren til samme datamodell som et liveopptak." },
  "upload.typeOptional": { nl: "Type (optioneel)", en: "Type (optional)", de: "Typ (optional)", fr: "Type (facultatif)", es: "Tipo (opcional)", it: "Tipo (opzionale)", pt: "Tipo (opcional)", pl: "Typ (opcjonalnie)", sv: "Typ (valfritt)", no: "Type (valgfritt)" },
  "dz.drop": { nl: "Sleep een .FIT hierheen of klik om te kiezen", en: "Drop a .FIT here or click to choose", de: "Zieh eine .FIT hierher oder klicke zum Auswählen", fr: "Déposez un .FIT ici ou cliquez pour choisir", es: "Suelta un .FIT aquí o haz clic para elegir", it: "Trascina un .FIT qui o clicca per scegliere", pt: "Arrasta um .FIT para aqui ou clica para escolher", pl: "Upuść .FIT tutaj lub kliknij, aby wybrać", sv: "Släpp en .FIT här eller klicka för att välja", no: "Slipp en .FIT her eller klikk for å velge" },
  "dz.hint": { nl: "max 25 MB · wordt automatisch geüpload zodra je een bestand kiest", en: "max 25 MB · uploads automatically once you pick a file", de: "max. 25 MB · lädt automatisch hoch, sobald du eine Datei wählst", fr: "max 25 Mo · s'importe automatiquement dès qu'un fichier est choisi", es: "máx 25 MB · se sube solo al elegir un archivo", it: "max 25 MB · si carica da solo quando scegli un file", pt: "máx 25 MB · carrega sozinho quando escolhes um ficheiro", pl: "maks. 25 MB · prześle się automatycznie po wybraniu pliku", sv: "max 25 MB · laddas upp automatiskt när du valt en fil", no: "maks 25 MB · lastes opp automatisk når du velger en fil" },
  "upload.parsing": { nl: "Bezig met uploaden en parsen van {f}…", en: "Uploading and parsing {f}…", de: "Lade hoch und verarbeite {f}…", fr: "Import et analyse de {f}…", es: "Subiendo y procesando {f}…", it: "Caricamento ed elaborazione di {f}…", pt: "A carregar e processar {f}…", pl: "Przesyłanie i przetwarzanie {f}…", sv: "Laddar upp och tolkar {f}…", no: "Laster opp og tolker {f}…" },
  "upload.fail": { nl: "Upload mislukt: {e}", en: "Upload failed: {e}", de: "Upload fehlgeschlagen: {e}", fr: "Échec de l'import : {e}", es: "Error al subir: {e}", it: "Caricamento non riuscito: {e}", pt: "Falha no carregamento: {e}", pl: "Przesyłanie nie powiodło się: {e}", sv: "Uppladdning misslyckades: {e}", no: "Opplasting mislyktes: {e}" },
  "upload.imported": { nl: "Sprong geïmporteerd (#{n})", en: "Jump imported (#{n})", de: "Sprung importiert (#{n})", fr: "Saut importé (#{n})", es: "Salto importado (#{n})", it: "Salto importato (#{n})", pt: "Salto importado (#{n})", pl: "Zaimportowano skok (#{n})", sv: "Hopp importerat (#{n})", no: "Hopp importert (#{n})" },
  "upload.tip": { nl: "Tip: maak eerst een normale activiteit-opname om de hele pijplijn te testen vóór een echte sprong.", en: "Tip: make a normal activity recording first to test the whole pipeline before a real jump.", de: "Tipp: Mach zuerst eine normale Aktivitätsaufzeichnung, um die ganze Kette vor einem echten Sprung zu testen.", fr: "Astuce : faites d'abord un enregistrement d'activité normal pour tester toute la chaîne avant un vrai saut.", es: "Consejo: haz primero una grabación de actividad normal para probar todo el flujo antes de un salto real.", it: "Suggerimento: fai prima una normale registrazione di attività per testare tutta la pipeline prima di un salto vero.", pt: "Dica: faz primeiro uma gravação de atividade normal para testar todo o fluxo antes de um salto real.", pl: "Wskazówka: najpierw nagraj zwykłą aktywność, aby przetestować cały proces przed prawdziwym skokiem.", sv: "Tips: gör först en vanlig aktivitetsinspelning för att testa hela kedjan före ett riktigt hopp.", no: "Tips: gjør først et vanlig aktivitetsopptak for å teste hele kjeden før et ekte hopp." },

  // profile
  "profile.title": { nl: "Profiel", en: "Profile", de: "Profil", fr: "Profil", es: "Perfil", it: "Profilo", pt: "Perfil", pl: "Profil", sv: "Profil", no: "Profil" },
  "profile.account": { nl: "Account", en: "Account", de: "Konto", fr: "Compte", es: "Cuenta", it: "Account", pt: "Conta", pl: "Konto", sv: "Konto", no: "Konto" },
  "profile.name": { nl: "Naam", en: "Name", de: "Name", fr: "Nom", es: "Nombre", it: "Nome", pt: "Nome", pl: "Imię", sv: "Namn", no: "Navn" },
  "profile.email": { nl: "E-mail", en: "Email", de: "E-Mail", fr: "E-mail", es: "Correo", it: "E-mail", pt: "E-mail", pl: "E-mail", sv: "E-post", no: "E-post" },
  "profile.logout": { nl: "Uitloggen", en: "Log out", de: "Abmelden", fr: "Se déconnecter", es: "Cerrar sesión", it: "Esci", pt: "Terminar sessão", pl: "Wyloguj", sv: "Logga ut", no: "Logg ut" },
  "profile.watchKey": { nl: "Watch-key (API)", en: "Watch key (API)", de: "Uhren-Key (API)", fr: "Clé montre (API)", es: "Clave del reloj (API)", it: "Chiave orologio (API)", pt: "Chave do relógio (API)", pl: "Klucz zegarka (API)", sv: "Klocknyckel (API)", no: "Klokkenøkkel (API)" },
  "profile.watchKeyHint": { nl: "Zet deze key in de Garmin-app (BlueSkies → instellingen → API-key) zodat je horloge sprongen naar jouw account stuurt.", en: "Put this key in the Garmin app (BlueSkies → settings → API key) so your watch sends jumps to your account.", de: "Trage diesen Key in der Garmin-App ein (BlueSkies → Einstellungen → API-Key), damit deine Uhr Sprünge an dein Konto sendet.", fr: "Mettez cette clé dans l'app Garmin (BlueSkies → réglages → clé API) pour que votre montre envoie les sauts vers votre compte.", es: "Pon esta clave en la app de Garmin (BlueSkies → ajustes → clave API) para que tu reloj envíe saltos a tu cuenta.", it: "Inserisci questa chiave nell'app Garmin (BlueSkies → impostazioni → chiave API) così l'orologio invia i salti al tuo account.", pt: "Coloca esta chave na app Garmin (BlueSkies → definições → chave API) para o teu relógio enviar saltos para a tua conta.", pl: "Wpisz ten klucz w aplikacji Garmin (BlueSkies → ustawienia → klucz API), aby zegarek wysyłał skoki na Twoje konto.", sv: "Lägg in nyckeln i Garmin-appen (BlueSkies → inställningar → API-nyckel) så skickar klockan hopp till ditt konto.", no: "Legg nøkkelen i Garmin-appen (BlueSkies → innstillinger → API-nøkkel) så sender klokka hopp til kontoen din." },
  "profile.yourKey": { nl: "Jouw API-key", en: "Your API key", de: "Dein API-Key", fr: "Votre clé API", es: "Tu clave API", it: "La tua chiave API", pt: "A tua chave API", pl: "Twój klucz API", sv: "Din API-nyckel", no: "Din API-nøkkel" },
  "btn.copy": { nl: "Kopieer", en: "Copy", de: "Kopieren", fr: "Copier", es: "Copiar", it: "Copia", pt: "Copiar", pl: "Kopiuj", sv: "Kopiera", no: "Kopier" },
  "btn.regen": { nl: "Vernieuw", en: "Regenerate", de: "Erneuern", fr: "Régénérer", es: "Regenerar", it: "Rigenera", pt: "Regenerar", pl: "Odnów", sv: "Förnya", no: "Forny" },
  "toast.copied": { nl: "Gekopieerd", en: "Copied", de: "Kopiert", fr: "Copié", es: "Copiado", it: "Copiato", pt: "Copiado", pl: "Skopiowano", sv: "Kopierat", no: "Kopiert" },
  "regen.confirm": { nl: "Nieuwe key genereren? De oude stopt direct met werken (watch opnieuw instellen).", en: "Generate a new key? The old one stops working immediately (reconfigure the watch).", de: "Neuen Key erzeugen? Der alte funktioniert sofort nicht mehr (Uhr neu einstellen).", fr: "Générer une nouvelle clé ? L'ancienne cesse de fonctionner immédiatement (reconfigurez la montre).", es: "¿Generar una nueva clave? La anterior deja de funcionar de inmediato (reconfigura el reloj).", it: "Generare una nuova chiave? La vecchia smette subito di funzionare (riconfigura l'orologio).", pt: "Gerar uma nova chave? A antiga deixa de funcionar imediatamente (reconfigura o relógio).", pl: "Wygenerować nowy klucz? Stary natychmiast przestaje działać (skonfiguruj zegarek ponownie).", sv: "Skapa en ny nyckel? Den gamla slutar fungera direkt (konfigurera om klockan).", no: "Lage ny nøkkel? Den gamle slutter å virke umiddelbart (konfigurer klokka på nytt)." },
  "toast.newKey": { nl: "Nieuwe key", en: "New key", de: "Neuer Key", fr: "Nouvelle clé", es: "Nueva clave", it: "Nuova chiave", pt: "Nova chave", pl: "Nowy klucz", sv: "Ny nyckel", no: "Ny nøkkel" },

  // login
  "login.signin": { nl: "Inloggen", en: "Sign in", de: "Anmelden", fr: "Connexion", es: "Iniciar sesión", it: "Accedi", pt: "Iniciar sessão", pl: "Zaloguj się", sv: "Logga in", no: "Logg inn" },
  "login.create": { nl: "Account aanmaken", en: "Create account", de: "Konto erstellen", fr: "Créer un compte", es: "Crear cuenta", it: "Crea account", pt: "Criar conta", pl: "Utwórz konto", sv: "Skapa konto", no: "Opprett konto" },
  "login.welcomeBack": { nl: "Welkom terug — log in om je logboek te zien.", en: "Welcome back — sign in to see your logbook.", de: "Willkommen zurück — melde dich an, um dein Logbuch zu sehen.", fr: "Bon retour — connectez-vous pour voir votre journal.", es: "Bienvenido de nuevo — inicia sesión para ver tu cuaderno.", it: "Bentornato — accedi per vedere il tuo registro.", pt: "Bem-vindo de volta — inicia sessão para ver o teu registo.", pl: "Witaj ponownie — zaloguj się, aby zobaczyć dziennik.", sv: "Välkommen tillbaka — logga in för att se din loggbok.", no: "Velkommen tilbake — logg inn for å se loggboken din." },
  "login.createSub": { nl: "Maak een account om je sprongen op te slaan.", en: "Create an account to save your jumps.", de: "Erstelle ein Konto, um deine Sprünge zu speichern.", fr: "Créez un compte pour enregistrer vos sauts.", es: "Crea una cuenta para guardar tus saltos.", it: "Crea un account per salvare i tuoi salti.", pt: "Cria uma conta para guardar os teus saltos.", pl: "Utwórz konto, aby zapisywać skoki.", sv: "Skapa ett konto för att spara dina hopp.", no: "Opprett en konto for å lagre hoppene dine." },
  "login.orEmail": { nl: "of met e-mail", en: "or with email", de: "oder mit E-Mail", fr: "ou avec un e-mail", es: "o con correo", it: "o con e-mail", pt: "ou com e-mail", pl: "lub e-mailem", sv: "eller med e-post", no: "eller med e-post" },
  "login.password": { nl: "Wachtwoord", en: "Password", de: "Passwort", fr: "Mot de passe", es: "Contraseña", it: "Password", pt: "Palavra-passe", pl: "Hasło", sv: "Lösenord", no: "Passord" },
  "login.nameOptional": { nl: "Naam (optioneel)", en: "Name (optional)", de: "Name (optional)", fr: "Nom (facultatif)", es: "Nombre (opcional)", it: "Nome (opzionale)", pt: "Nome (opcional)", pl: "Imię (opcjonalnie)", sv: "Namn (valfritt)", no: "Navn (valgfritt)" },
  "login.namePlaceholder": { nl: "Je naam", en: "Your name", de: "Dein Name", fr: "Votre nom", es: "Tu nombre", it: "Il tuo nome", pt: "O teu nome", pl: "Twoje imię", sv: "Ditt namn", no: "Navnet ditt" },
  "login.noAccount": { nl: "Nog geen account? ", en: "No account yet? ", de: "Noch kein Konto? ", fr: "Pas encore de compte ? ", es: "¿Aún no tienes cuenta? ", it: "Non hai un account? ", pt: "Ainda sem conta? ", pl: "Nie masz konta? ", sv: "Inget konto än? ", no: "Ingen konto ennå? " },
  "login.makeOne": { nl: "Maak er een", en: "Create one", de: "Erstelle eins", fr: "Créez-en un", es: "Crea una", it: "Creane uno", pt: "Cria uma", pl: "Utwórz je", sv: "Skapa ett", no: "Opprett en" },
  "login.haveAccount": { nl: "Al een account? ", en: "Already have an account? ", de: "Schon ein Konto? ", fr: "Déjà un compte ? ", es: "¿Ya tienes cuenta? ", it: "Hai già un account? ", pt: "Já tens conta? ", pl: "Masz już konto? ", sv: "Har du redan ett konto? ", no: "Har du allerede konto? " },
  "login.doLogin": { nl: "Log in", en: "Sign in", de: "Anmelden", fr: "Connectez-vous", es: "Inicia sesión", it: "Accedi", pt: "Inicia sessão", pl: "Zaloguj się", sv: "Logga in", no: "Logg inn" },
  "lang.label": { nl: "Taal", en: "Language", de: "Sprache", fr: "Langue", es: "Idioma", it: "Lingua", pt: "Idioma", pl: "Język", sv: "Språk", no: "Språk" },

  // server error codes
  "err.bad_credentials": { nl: "Onjuist e-mailadres of wachtwoord.", en: "Incorrect email or password.", de: "Falsche E-Mail oder Passwort.", fr: "E-mail ou mot de passe incorrect.", es: "Correo o contraseña incorrectos.", it: "Email o password errati.", pt: "E-mail ou palavra-passe incorretos.", pl: "Błędny e-mail lub hasło.", sv: "Fel e-post eller lösenord.", no: "Feil e-post eller passord." },
  "err.email_taken": { nl: "Er bestaat al een account met dit e-mailadres.", en: "An account with this email already exists.", de: "Es existiert bereits ein Konto mit dieser E-Mail.", fr: "Un compte avec cet e-mail existe déjà.", es: "Ya existe una cuenta con este correo.", it: "Esiste già un account con questa email.", pt: "Já existe uma conta com este e-mail.", pl: "Konto z tym e-mailem już istnieje.", sv: "Ett konto med denna e-post finns redan.", no: "En konto med denne e-posten finnes allerede." },
  "err.password_too_short": { nl: "Wachtwoord moet minstens 8 tekens zijn.", en: "Password must be at least 8 characters.", de: "Passwort muss mindestens 8 Zeichen haben.", fr: "Le mot de passe doit faire au moins 8 caractères.", es: "La contraseña debe tener al menos 8 caracteres.", it: "La password deve avere almeno 8 caratteri.", pt: "A palavra-passe deve ter pelo menos 8 caracteres.", pl: "Hasło musi mieć co najmniej 8 znaków.", sv: "Lösenordet måste vara minst 8 tecken.", no: "Passordet må være minst 8 tegn." },
  "err.email_password_required": { nl: "E-mail en wachtwoord verplicht.", en: "Email and password are required.", de: "E-Mail und Passwort erforderlich.", fr: "E-mail et mot de passe requis.", es: "Correo y contraseña obligatorios.", it: "Email e password obbligatorie.", pt: "E-mail e palavra-passe obrigatórios.", pl: "E-mail i hasło są wymagane.", sv: "E-post och lösenord krävs.", no: "E-post og passord kreves." },
  "err.rate_limited": { nl: "Te veel pogingen. Wacht even en probeer opnieuw.", en: "Too many attempts. Please wait and try again.", de: "Zu viele Versuche. Bitte kurz warten.", fr: "Trop de tentatives. Patientez un instant.", es: "Demasiados intentos. Espera un momento.", it: "Troppi tentativi. Attendi un momento.", pt: "Demasiadas tentativas. Aguarda um momento.", pl: "Zbyt wiele prób. Poczekaj chwilę.", sv: "För många försök. Vänta en stund.", no: "For mange forsøk. Vent litt." },
  "err.google_failed": { nl: "Google-login mislukt.", en: "Google sign-in failed.", de: "Google-Anmeldung fehlgeschlagen.", fr: "Échec de la connexion Google.", es: "Error al iniciar sesión con Google.", it: "Accesso con Google non riuscito.", pt: "Falha no início de sessão com Google.", pl: "Logowanie Google nie powiodło się.", sv: "Google-inloggning misslyckades.", no: "Google-innlogging mislyktes." },
  "err.reset_invalid": { nl: "Deze reset-link is ongeldig of verlopen.", en: "This reset link is invalid or has expired." },

  // password reset / forgot
  "login.forgot": { nl: "Wachtwoord vergeten?", en: "Forgot password?" },
  "forgot.title": { nl: "Wachtwoord herstellen", en: "Reset password" },
  "forgot.sub": { nl: "Vul je e-mail in; we sturen een reset-link.", en: "Enter your email and we'll send a reset link." },
  "forgot.submit": { nl: "Stuur reset-link", en: "Send reset link" },
  "forgot.sent": { nl: "Als dat e-mailadres bestaat, is er een reset-link verstuurd.", en: "If that email exists, a reset link has been sent." },
  "reset.title": { nl: "Nieuw wachtwoord", en: "New password" },
  "reset.sub": { nl: "Kies een nieuw wachtwoord voor je account.", en: "Choose a new password for your account." },
  "reset.submit": { nl: "Wachtwoord opslaan", en: "Save password" },

  // disclaimer + privacy + export
  "disclaimer.short": { nl: "Geen veiligheidsinstrument; vrije-val-data zijn schattingen.", en: "Not a safety device; freefall data are estimates." },
  "footer.privacy": { nl: "Privacy & disclaimer", en: "Privacy & disclaimer" },
  "profile.export": { nl: "Download mijn data (.json)", en: "Download my data (.json)" },
  "profile.data": { nl: "Mijn gegevens", en: "My data" },
  "privacy.title": { nl: "Privacy & disclaimer", en: "Privacy & disclaimer" },
  "disclaimer.full": {
    nl: "BlueSkies is een persoonlijk naslag-logboek, GÉÉN veiligheidsinstrument en GÉÉN hoogtemeter. Absolute vrije-val-hoogte en verticale snelheid zijn schattingen (de barometer is onbetrouwbaar tijdens de vrije val). Gebruik altijd een goedgekeurde hoogtemeter en een AAD. In Nederland zijn een papieren logboek, een AAD en een aparte hoogtemeter wettelijk verplicht; deze app vervangt die niet.",
    en: "BlueSkies is a personal reference logbook, NOT a safety instrument and NOT an altimeter. Absolute freefall altitude and vertical speed are estimates (the barometer is unreliable during freefall). Always use an approved altimeter and an AAD. This app does not replace mandatory equipment or any legally required paper logbook.",
  },
  "privacy.body": {
    nl: "Privacy: we bewaren je naam, e-mailadres en je sprong-data (GPS-track, hoogte, hartslag) om je logboek te tonen. Data staat op een server in de EU (Frankfurt) en wordt niet met derden gedeeld of verkocht. Inloggen met Google gebruikt alleen je naam/e-mail. Je kunt sprongen altijd verwijderen en je data downloaden; vraag accountverwijdering via de beheerder.\n\n" +
      "Disclaimer: BlueSkies is een persoonlijk naslag-logboek, géén veiligheidsinstrument en géén hoogtemeter. Vrije-val-hoogte en -snelheid zijn schattingen. Gebruik altijd een goedgekeurde hoogtemeter en AAD. Een papieren logboek, AAD en aparte hoogtemeter zijn wettelijk verplicht; deze app vervangt die niet.",
    en: "Privacy: we store your name, email and jump data (GPS track, altitude, heart rate) to show your logbook. Data is hosted on a server in the EU (Frankfurt) and is never shared or sold. Google sign-in only uses your name/email. You can delete jumps and download your data anytime; request account deletion via the administrator.\n\n" +
      "Disclaimer: BlueSkies is a personal reference logbook, not a safety instrument and not an altimeter. Freefall altitude and speed are estimates. Always use an approved altimeter and AAD. A paper logbook, AAD and separate altimeter are legally required; this app does not replace them.",
  },
};

let LANG = localStorage.getItem("bs_lang");
if (!LANG || !LANGS.some((l) => l.code === LANG)) {
  const nav = (navigator.language || "en").slice(0, 2);
  LANG = LANGS.some((l) => l.code === nav) ? nav : "nl";
}

export function getLang() { return LANG; }
export function setLang(code) {
  if (!LANGS.some((l) => l.code === code)) return;
  localStorage.setItem("bs_lang", code);
  LANG = code;
  document.documentElement.lang = code;
  location.reload();
}

export function t(key, vars) {
  const entry = STR[key];
  let s = entry ? (entry[LANG] ?? entry.en ?? key) : key;
  if (vars) {
    // plural helper: {s} -> "s" (en/nl/de/...) when n != 1, else ""
    if ("n" in vars && s.includes("{s}")) {
      s = s.replace("{s}", vars.n === 1 ? "" : pluralSuffix());
    }
    for (const k in vars) s = s.replaceAll("{" + k + "}", vars[k]);
  }
  return s;
}
function pluralSuffix() {
  // simple suffix for the few plural strings; languages without a clean suffix
  // keep the singular noun (acceptable for "5 hopp" etc).
  return { nl: "en", en: "s", de: "ünge", fr: "s", es: "s", it: "i", pt: "s", pl: "i", sv: "", no: "" }[LANG] ?? "";
}

document.documentElement.lang = LANG;
